apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ecommerce
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3Jk  # "rootpassword" base64 encoded
  database: ZWNvbW1lcmNlX2Ri  # "ecommerce_db" base64 encoded
  username: ZWNvbW1lcmNlX3VzZXI=  # "ecommerce_user" base64 encoded
  password: dXNlcnBhc3N3b3Jk  # "userpassword" base64 encoded
